services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.server
    links:
      - storage
  proxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    links:
      - app
    ports:
      - "80:80"
  storage:
    image: redis

