services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.server
    links:
      - storage
    environment:
      - APP_HOST=app
      - STORAGE_HOST=storage
      - GIN_MODE=release
    env_file: 
      - secrets.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.https.rule=Host(`secretskeeper.xyz`)"
      - "traefik.http.routers.https.entrypoints=https"
      - "traefik.http.routers.https.tls=true"
      - "traefik.http.routers.https.tls.certresolver=letsencrypt"
      - "traefik.http.services.https.loadbalancer.server.port=8888"
  proxy:
    image: "traefik:v2.5.6"
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.http.http.redirections.entryPoint.to=https"
      - "--entrypoints.http.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.http.http.redirections.entryPoint.permanent=true"
      - "--entrypoints.https.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http"
      - "--certificatesresolvers.letsencrypt.acme.email=lightlocdog@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./data/letsencrypt:/letsencrypt"
  storage:
    image: redis

