services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.server
    links:
      - storage
    environment:
      - APP_HOST=app
      - STORAGE_HOST=storage
      - GIN_MODE=release
    env_file: 
      - secrets.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.registry.rule=Host(`secretskeeper.xyz`)"
      - "traefik.http.services.registry.loadbalancer.server.port=8888"
  proxy:
    image: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  storage:
    image: redis

