services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.server
    links:
      - storage
    environment:
      - APP_HOST=app
      - STORAGE_HOST=storage
      - GIN_MODE=release
    env_file: 
      - secrets.env
  proxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    links:
      - app
    ports:
      - "80:80"
  storage:
    image: redis

